### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by s-a-m** [P2Pvalue/p2pvalue-website-code#26]
There are multiple versions of the logo. I personally like these two:
http://p2pvalue.eu/sites/all/themes/CSS2948/logo.png
http://caps2020.eu/wp-content/uploads/2014/01/P2PValue_logo-semihorizontal.png
which are fortunately the most common (in the web, in the deliverables). However, there are other versions (in the ppt template) which I find much uglier :)  e.g. http://zzzinc.net/wp-content/uploads/P2PVDATAJAM.png  

It'd be good to normalize the logos, hopefully avoiding the "uglier" ones. This is of course subjective, although I think this preference resonates in others (I might be wrong).

**Comment by drozas** [comment]
@cataspanglish / James, I'll reassign this to you, since this is related to the creation of contents.
