### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by s-a-m** [P2Pvalue/p2pvalue-website-code#27]
The website has a grey background colour which I think damages the reading, especially when there are bold sentences, e.g. http://p2pvalue.eu/blog/viability-design-guidelines
Probably another background, lighter, would help. I'm not a designer though, so I don't know which should be the appropriate combination of colours.

**Comment by s-a-m** [comment]
Related: #33

**Comment by drozas** [comment]
@cataspanglish / James, I'll reassign this to you, since this is related to the creation of a new design and its implementation via theming.
