### ISSUE TITLE
Bold

### ISSUE THREAD

**Issue by s-a-m** [P2Pvalue/p2pvalue-website-code#28]
The bold should be corrected in the CSS. Typically it's not very strong (and thus barely noticed), except when David explicitly modifies the CSS. 

See the bold here, in the post beginning, unnoticeable:
http://p2pvalue.eu/blog/2nd-floss4p2p-workshop-call-proposals
and see the modified CSS strong bold:
http://p2pvalue.eu/floss4p2p-workshop-agenda

This makes it difficult to "read fast" the text, as highlighting in bold is not useful.

**Comment by drozas** [comment]
@cataspanglish / James, I'll reassign this to you, since this could be included as a "minor" of the new theme.
