### ISSUE TITLE
Responsive menu does not forward

### ISSUE THREAD

**Issue by drozas** [P2Pvalue/p2pvalue-website-code#3]
This is a theming issue which relates to the responsive menu not forwarding to the link

**Comment by drozas** [comment]
@cataspanglish How we should proceed to do this? Could you contact the company who develop the theme? I will update the base theme beforehand as well (adaptive theme), as part of #1

**Comment by cataspanglish** [comment]
what is the issue exactly - which link is not resolving?

**Comment by drozas** [comment]
Hi @cataspanglish. This is affecting the main menu, trying from an Android phone with the default browser. The directory seems not be affected by this.

**Comment by drozas** [comment]
@lifesized will contact Sparx about this
