### ISSUE TITLE
License code

### ISSUE THREAD

**Issue by s-a-m** [P2Pvalue/p2pvalue-website-code#31]
The CC license does not include the semantic code, and thus it is not trackable by Google or other search engines as CC-licensed text or images. Thus, when searching for CC-licensed images in Google Images, no one can find the P2Pvalue.eu images: http://ur1.ca/njjki  You can find the semantic code here: https://creativecommons.org/choose/

Also, I think not highlighting the CC icon is a mistake. Not just for machines (which don't care) but for humans: it's just showing clearly that the contents are free (as in free speech) and that we welcome reusability. Thus, I would add the CC BY SA logo on the right side-bar.

**Comment by drozas** [comment]
Done. I have merged the tags from the code generator suggested by @s-a-m with the current text.

**Comment by drozas** [comment]
Reviewing code is not filtered by Drupal. Final outpu (from firebug):

```
<div class="float-l data-section">
<p>
<span property="dct:title" xmlns:dct="http://purl.org/dc/terms/">The contens of this website </span>
are licensed under a
<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>
except if otherwise noted.
<br>
The source code is licensed under a
<a rel="license" href="http://www.gnu.org/licenses/gpl.html"> GPLv3 License</a>
and can be checkout from
<a rel="github-repo" href="https://github.com/P2Pvalue/p2pvalue-website-code">Github</a>
. Click
<a href="http://www.p2pvalue.eu/user">here to login as a consortium member</a>
.
</p>
<p>
<a href="http://creativecommons.org/licenses/by-sa/4.0/" rel="license">
</p>
<p>Disclaimer: The views expressed in this website do not necessarily reflect the views of the EC.</p>
</div>
```

**Comment by drozas** [comment]
@s-a-m , I have placed the icon in the same block. By the right sidebar you mean on the right of the footer region (flags) or the actual right sidebar region? I attached a screenshot with the regions in this area (some of them are not available for cellphones/tablets):

![screenshot from 2015-08-25 11 41 42](https://cloud.githubusercontent.com/assets/1962473/9464754/6cacb9a0-4b1e-11e5-9a5b-642a0893ba7d.png)

**Comment by s-a-m** [comment]
LGTM

On Tue, Aug 25, 2015 at 12:43 PM, David Rozas notifications@github.com
wrote:

> @s-a-m https://github.com/s-a-m , I have placed the icon in the same
> block. By the right sidebar you mean on the right of the footer region
> (flags) or the actual right sidebar region? I attached a screenshot with
> the regions in this area (some of them are not available for
> cellphones/tablets):
> 
> [image: screenshot from 2015-08-25 11 41 42]
> https://cloud.githubusercontent.com/assets/1962473/9464754/6cacb9a0-4b1e-11e5-9a5b-642a0893ba7d.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/P2Pvalue/p2pvalue-website-code/issues/31#issuecomment-134552675
> .

## 

Samer

"We are the ones we have been waiting for" (June Jordan)

**Comment by drozas** [comment]
Great, I'll mark this as closed then ;-)
