### ISSUE TITLE
Headings

### ISSUE THREAD

**Issue by s-a-m** [P2Pvalue/p2pvalue-website-code#32]
Is it normal that a H3 heading is smaller than the normal style? e.g. http://p2pvalue.eu/consortium

I think the headings style, and/or the font, should be double-checked.

**Comment by drozas** [comment]
@cataspanglish / James, I'll reassign this to you, since this could be included as a "minor" of the new theme.

**Comment by drozas** [comment]
@cataspanglish / James, I'll reassign this to you, since this could be included as a "minor" of the new theme.
