### ISSUE TITLE
Background bottom

### ISSUE THREAD

**Issue by s-a-m** [P2Pvalue/p2pvalue-website-code#33]
The grey background has a small design in the end, in which it is becomes a stronger grey, using the triangles of the P2Pvalue logo but in grey. Again, I'm not a designer but I don't find it really appealing, but rather ugly. Furthermore when it is the design that we must respect also in the P2Pvalue platform, where it appears really not nice:
https://p.p2pvalue.eu/#/frontpage

If the background grey is changed (issue #27) It'd be good to change also the background bottom for a different, nicer, design.

**Comment by drozas** [comment]
@cataspanglish / James, I'll reassign this to you, since this could be included as part of the new design and its implementation (theming)
