### ISSUE TITLE
Paragraph spacing

### ISSUE THREAD

**Issue by s-a-m** [P2Pvalue/p2pvalue-website-code#35]
The paragraphs are way too separated from each other, example: http://p2pvalue.eu/floss4p2p-book-open-call  Either we don't introduce line-break and then it's too stuck together, or we do and then it's way too separated. This can be easily corrected in the CSS.

**Comment by drozas** [comment]
Thanks Samer, I will take a look at this

**Comment by drozas** [comment]
Reassigning this to P2PF, after they informed us (December meeting) they are working on a new full design.
